// automatically generated by the FlatBuffers compiler, do not modify

/**
 * должно соответствовать DrawingType в DrawingModel.h
 */
export enum DrawingType {
  None = -1,
  HorizontalLine = 0,
  VerticalLine = 1,
  TrendLine = 2,
  FixedTrend = 3,
  Ray = 4,
  FibonacciLevels = 5,
  FibonacciFan = 6
}
