// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DrawingModel4, DrawingModel4T } from '../../milky/drawing/drawing-model4.js';


export class EditedDrawingNotify4 implements flatbuffers.IUnpackableObject<EditedDrawingNotify4T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EditedDrawingNotify4 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEditedDrawingNotify4(bb:flatbuffers.ByteBuffer, obj?:EditedDrawingNotify4):EditedDrawingNotify4 {
  return (obj || new EditedDrawingNotify4()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEditedDrawingNotify4(bb:flatbuffers.ByteBuffer, obj?:EditedDrawingNotify4):EditedDrawingNotify4 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EditedDrawingNotify4()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

model(obj?:DrawingModel4):DrawingModel4|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DrawingModel4()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startEditedDrawingNotify4(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addModel(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, modelOffset, 0);
}

static endEditedDrawingNotify4(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // model
  return offset;
}

static createEditedDrawingNotify4(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset):flatbuffers.Offset {
  EditedDrawingNotify4.startEditedDrawingNotify4(builder);
  EditedDrawingNotify4.addModel(builder, modelOffset);
  return EditedDrawingNotify4.endEditedDrawingNotify4(builder);
}

unpack(): EditedDrawingNotify4T {
  return new EditedDrawingNotify4T(
    (this.model() !== null ? this.model()!.unpack() : null)
  );
}


unpackTo(_o: EditedDrawingNotify4T): void {
  _o.model = (this.model() !== null ? this.model()!.unpack() : null);
}
}

export class EditedDrawingNotify4T implements flatbuffers.IGeneratedObject {
constructor(
  public model: DrawingModel4T|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const model = (this.model !== null ? this.model!.pack(builder) : 0);

  return EditedDrawingNotify4.createEditedDrawingNotify4(builder,
    model
  );
}
}
