// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DrawingModel, DrawingModelT } from '../../milky/drawing/drawing-model.js';


export class EditedDrawingNotify implements flatbuffers.IUnpackableObject<EditedDrawingNotifyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EditedDrawingNotify {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEditedDrawingNotify(bb:flatbuffers.ByteBuffer, obj?:EditedDrawingNotify):EditedDrawingNotify {
  return (obj || new EditedDrawingNotify()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEditedDrawingNotify(bb:flatbuffers.ByteBuffer, obj?:EditedDrawingNotify):EditedDrawingNotify {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EditedDrawingNotify()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

model(obj?:DrawingModel):DrawingModel|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DrawingModel()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startEditedDrawingNotify(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addModel(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, modelOffset, 0);
}

static endEditedDrawingNotify(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // model
  return offset;
}

static createEditedDrawingNotify(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset):flatbuffers.Offset {
  EditedDrawingNotify.startEditedDrawingNotify(builder);
  EditedDrawingNotify.addModel(builder, modelOffset);
  return EditedDrawingNotify.endEditedDrawingNotify(builder);
}

unpack(): EditedDrawingNotifyT {
  return new EditedDrawingNotifyT(
    (this.model() !== null ? this.model()!.unpack() : null)
  );
}


unpackTo(_o: EditedDrawingNotifyT): void {
  _o.model = (this.model() !== null ? this.model()!.unpack() : null);
}
}

export class EditedDrawingNotifyT implements flatbuffers.IGeneratedObject {
constructor(
  public model: DrawingModelT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const model = (this.model !== null ? this.model!.pack(builder) : 0);

  return EditedDrawingNotify.createEditedDrawingNotify(builder,
    model
  );
}
}
