// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class RemoveAllDrawingsMethod implements flatbuffers.IUnpackableObject<RemoveAllDrawingsMethodT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RemoveAllDrawingsMethod {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRemoveAllDrawingsMethod(bb:flatbuffers.ByteBuffer, obj?:RemoveAllDrawingsMethod):RemoveAllDrawingsMethod {
  return (obj || new RemoveAllDrawingsMethod()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRemoveAllDrawingsMethod(bb:flatbuffers.ByteBuffer, obj?:RemoveAllDrawingsMethod):RemoveAllDrawingsMethod {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RemoveAllDrawingsMethod()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRemoveAllDrawingsMethod(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRemoveAllDrawingsMethod(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRemoveAllDrawingsMethod(builder:flatbuffers.Builder):flatbuffers.Offset {
  RemoveAllDrawingsMethod.startRemoveAllDrawingsMethod(builder);
  return RemoveAllDrawingsMethod.endRemoveAllDrawingsMethod(builder);
}

unpack(): RemoveAllDrawingsMethodT {
  return new RemoveAllDrawingsMethodT();
}


unpackTo(_o: RemoveAllDrawingsMethodT): void {}
}

export class RemoveAllDrawingsMethodT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RemoveAllDrawingsMethod.createRemoveAllDrawingsMethod(builder);
}
}
