// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class AdviserId {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AdviserId {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAdviserId(bb:flatbuffers.ByteBuffer, obj?:AdviserId):AdviserId {
  return (obj || new AdviserId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAdviserId(bb:flatbuffers.ByteBuffer, obj?:AdviserId):AdviserId {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AdviserId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startAdviserId(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endAdviserId(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAdviserId(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  AdviserId.startAdviserId(builder);
  AdviserId.addId(builder, id);
  return AdviserId.endAdviserId(builder);
}

unpack(): AdviserIdT {
  return new AdviserIdT(
    this.id()
  );
}


unpackTo(_o: AdviserIdT): void {
  _o.id = this.id();
}
}

export class AdviserIdT {
constructor(
  public id: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return AdviserId.createAdviserId(builder,
    this.id
  );
}
}
