// automatically generated by the FlatBuffers compiler, do not modify

export { ClientReply, ClientReplyT } from './resources/client-reply.js';
export { DynamicResource, DynamicResourceT } from './resources/dynamic-resource.js';
export { LoadTextureAtlasFromClientRequest, LoadTextureAtlasFromClientRequestT } from './resources/load-texture-atlas-from-client-request.js';
export { Methods } from './resources/methods.js';
export { Notify, NotifyT } from './resources/notify.js';
export { Request, RequestT } from './resources/request.js';
export { Resource, ResourceT } from './resources/resource.js';
export { ResourceRequest } from './resources/resource-request.js';
export { StaticResource, StaticResourceT } from './resources/static-resource.js';
export { StaticResourceType } from './resources/static-resource-type.js';
export * as adviser from './milky/model/adviser.js';
export * as deal from './milky/model/deal.js';
export * as deal_limits from './milky/model/deal-limits.js';
export * as deal_profit_scale from './milky/model/deal-profit-scale.js';
export * as indicator from './milky/model/indicator.js';
export * as layout from './milky/model/layout.js';
export * as quotes from './milky/model/quotes.js';
export * as strike from './milky/model/strike.js';
export * as version from './milky/model/version.js';
