// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class FinishOnboarding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FinishOnboarding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFinishOnboarding(bb:flatbuffers.ByteBuffer, obj?:FinishOnboarding):FinishOnboarding {
  return (obj || new FinishOnboarding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFinishOnboarding(bb:flatbuffers.ByteBuffer, obj?:FinishOnboarding):FinishOnboarding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FinishOnboarding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startFinishOnboarding(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endFinishOnboarding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFinishOnboarding(builder:flatbuffers.Builder):flatbuffers.Offset {
  FinishOnboarding.startFinishOnboarding(builder);
  return FinishOnboarding.endFinishOnboarding(builder);
}

unpack(): FinishOnboardingT {
  return new FinishOnboardingT();
}


unpackTo(_o: FinishOnboardingT): void {}
}

export class FinishOnboardingT {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FinishOnboarding.createFinishOnboarding(builder);
}
}
