// automatically generated by the FlatBuffers compiler, do not modify

import { FinishOnboarding, FinishOnboardingT } from '../../milky/onboarding/finish-onboarding';
import { FinishOnboardingDeal, FinishOnboardingDealT } from '../../milky/onboarding/finish-onboarding-deal';
import { HideDirectionsAreas, HideDirectionsAreasT } from '../../milky/onboarding/hide-directions-areas';
import { HidePossibleCharts, HidePossibleChartsT } from '../../milky/onboarding/hide-possible-charts';
import { ShowDirectionsAreas, ShowDirectionsAreasT } from '../../milky/onboarding/show-directions-areas';
import { ShowPossibleCharts, ShowPossibleChartsT } from '../../milky/onboarding/show-possible-charts';
import { StartLastCandleAnimation, StartLastCandleAnimationT } from '../../milky/onboarding/start-last-candle-animation';
import { StartOnboarding, StartOnboardingT } from '../../milky/onboarding/start-onboarding';
import { StopLastCandleAnimation, StopLastCandleAnimationT } from '../../milky/onboarding/stop-last-candle-animation';


export enum Methods {
  NONE = 0,
  ShowPossibleCharts = 1,
  HidePossibleCharts = 2,
  ShowDirectionsAreas = 3,
  HideDirectionsAreas = 4,
  StartLastCandleAnimation = 5,
  StopLastCandleAnimation = 6,
  StartOnboarding = 7,
  FinishOnboarding = 8,
  FinishOnboardingDeal = 9
}

export function unionToMethods(
  type: Methods,
  accessor: (obj:FinishOnboarding|FinishOnboardingDeal|HideDirectionsAreas|HidePossibleCharts|ShowDirectionsAreas|ShowPossibleCharts|StartLastCandleAnimation|StartOnboarding|StopLastCandleAnimation) => FinishOnboarding|FinishOnboardingDeal|HideDirectionsAreas|HidePossibleCharts|ShowDirectionsAreas|ShowPossibleCharts|StartLastCandleAnimation|StartOnboarding|StopLastCandleAnimation|null
): FinishOnboarding|FinishOnboardingDeal|HideDirectionsAreas|HidePossibleCharts|ShowDirectionsAreas|ShowPossibleCharts|StartLastCandleAnimation|StartOnboarding|StopLastCandleAnimation|null {
  switch(Methods[type]) {
    case 'NONE': return null; 
    case 'ShowPossibleCharts': return accessor(new ShowPossibleCharts())! as ShowPossibleCharts;
    case 'HidePossibleCharts': return accessor(new HidePossibleCharts())! as HidePossibleCharts;
    case 'ShowDirectionsAreas': return accessor(new ShowDirectionsAreas())! as ShowDirectionsAreas;
    case 'HideDirectionsAreas': return accessor(new HideDirectionsAreas())! as HideDirectionsAreas;
    case 'StartLastCandleAnimation': return accessor(new StartLastCandleAnimation())! as StartLastCandleAnimation;
    case 'StopLastCandleAnimation': return accessor(new StopLastCandleAnimation())! as StopLastCandleAnimation;
    case 'StartOnboarding': return accessor(new StartOnboarding())! as StartOnboarding;
    case 'FinishOnboarding': return accessor(new FinishOnboarding())! as FinishOnboarding;
    case 'FinishOnboardingDeal': return accessor(new FinishOnboardingDeal())! as FinishOnboardingDeal;
    default: return null;
  }
}

export function unionListToMethods(
  type: Methods, 
  accessor: (index: number, obj:FinishOnboarding|FinishOnboardingDeal|HideDirectionsAreas|HidePossibleCharts|ShowDirectionsAreas|ShowPossibleCharts|StartLastCandleAnimation|StartOnboarding|StopLastCandleAnimation) => FinishOnboarding|FinishOnboardingDeal|HideDirectionsAreas|HidePossibleCharts|ShowDirectionsAreas|ShowPossibleCharts|StartLastCandleAnimation|StartOnboarding|StopLastCandleAnimation|null, 
  index: number
): FinishOnboarding|FinishOnboardingDeal|HideDirectionsAreas|HidePossibleCharts|ShowDirectionsAreas|ShowPossibleCharts|StartLastCandleAnimation|StartOnboarding|StopLastCandleAnimation|null {
  switch(Methods[type]) {
    case 'NONE': return null; 
    case 'ShowPossibleCharts': return accessor(index, new ShowPossibleCharts())! as ShowPossibleCharts;
    case 'HidePossibleCharts': return accessor(index, new HidePossibleCharts())! as HidePossibleCharts;
    case 'ShowDirectionsAreas': return accessor(index, new ShowDirectionsAreas())! as ShowDirectionsAreas;
    case 'HideDirectionsAreas': return accessor(index, new HideDirectionsAreas())! as HideDirectionsAreas;
    case 'StartLastCandleAnimation': return accessor(index, new StartLastCandleAnimation())! as StartLastCandleAnimation;
    case 'StopLastCandleAnimation': return accessor(index, new StopLastCandleAnimation())! as StopLastCandleAnimation;
    case 'StartOnboarding': return accessor(index, new StartOnboarding())! as StartOnboarding;
    case 'FinishOnboarding': return accessor(index, new FinishOnboarding())! as FinishOnboarding;
    case 'FinishOnboardingDeal': return accessor(index, new FinishOnboardingDeal())! as FinishOnboardingDeal;
    default: return null;
  }
}
