// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ShowDirectionsAreas implements flatbuffers.IUnpackableObject<ShowDirectionsAreasT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): ShowDirectionsAreas {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsShowDirectionsAreas(bb: flatbuffers.ByteBuffer, obj?: ShowDirectionsAreas): ShowDirectionsAreas {
    return (obj || new ShowDirectionsAreas()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsShowDirectionsAreas(
    bb: flatbuffers.ByteBuffer,
    obj?: ShowDirectionsAreas,
  ): ShowDirectionsAreas {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new ShowDirectionsAreas()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startShowDirectionsAreas(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endShowDirectionsAreas(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createShowDirectionsAreas(builder: flatbuffers.Builder): flatbuffers.Offset {
    ShowDirectionsAreas.startShowDirectionsAreas(builder);
    return ShowDirectionsAreas.endShowDirectionsAreas(builder);
  }

  unpack(): ShowDirectionsAreasT {
    return new ShowDirectionsAreasT();
  }

  unpackTo(_o: ShowDirectionsAreasT): void {}
}

export class ShowDirectionsAreasT implements flatbuffers.IGeneratedObject {
  constructor() {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    return ShowDirectionsAreas.createShowDirectionsAreas(builder);
  }
}
