// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DrawingModel, DrawingModelT } from '../../milky/drawing/drawing-model.js';


export class CreatedDrawingNotify implements flatbuffers.IUnpackableObject<CreatedDrawingNotifyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreatedDrawingNotify {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreatedDrawingNotify(bb:flatbuffers.ByteBuffer, obj?:CreatedDrawingNotify):CreatedDrawingNotify {
  return (obj || new CreatedDrawingNotify()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreatedDrawingNotify(bb:flatbuffers.ByteBuffer, obj?:CreatedDrawingNotify):CreatedDrawingNotify {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreatedDrawingNotify()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

model(obj?:DrawingModel):DrawingModel|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DrawingModel()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCreatedDrawingNotify(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addModel(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, modelOffset, 0);
}

static endCreatedDrawingNotify(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // model
  return offset;
}

static createCreatedDrawingNotify(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset):flatbuffers.Offset {
  CreatedDrawingNotify.startCreatedDrawingNotify(builder);
  CreatedDrawingNotify.addModel(builder, modelOffset);
  return CreatedDrawingNotify.endCreatedDrawingNotify(builder);
}

unpack(): CreatedDrawingNotifyT {
  return new CreatedDrawingNotifyT(
    (this.model() !== null ? this.model()!.unpack() : null)
  );
}


unpackTo(_o: CreatedDrawingNotifyT): void {
  _o.model = (this.model() !== null ? this.model()!.unpack() : null);
}
}

export class CreatedDrawingNotifyT implements flatbuffers.IGeneratedObject {
constructor(
  public model: DrawingModelT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const model = (this.model !== null ? this.model!.pack(builder) : 0);

  return CreatedDrawingNotify.createCreatedDrawingNotify(builder,
    model
  );
}
}
