// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Rect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Rect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readFloat32(this.bb_pos);
}

y():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

width():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

height():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createRect(builder:flatbuffers.Builder, x: number, y: number, width: number, height: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeFloat32(height);
  builder.writeFloat32(width);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
}


unpack(): RectT {
  return new RectT(
    this.x(),
    this.y(),
    this.width(),
    this.height()
  );
}


unpackTo(_o: RectT): void {
  _o.x = this.x();
  _o.y = this.y();
  _o.width = this.width();
  _o.height = this.height();
}
}

export class RectT {
constructor(
  public x: number = 0.0,
  public y: number = 0.0,
  public width: number = 0.0,
  public height: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Rect.createRect(builder,
    this.x,
    this.y,
    this.width,
    this.height
  );
}
}
