// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class HideProfitScaleForSelectedDeal {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HideProfitScaleForSelectedDeal {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHideProfitScaleForSelectedDeal(bb:flatbuffers.ByteBuffer, obj?:HideProfitScaleForSelectedDeal):HideProfitScaleForSelectedDeal {
  return (obj || new HideProfitScaleForSelectedDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHideProfitScaleForSelectedDeal(bb:flatbuffers.ByteBuffer, obj?:HideProfitScaleForSelectedDeal):HideProfitScaleForSelectedDeal {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HideProfitScaleForSelectedDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startHideProfitScaleForSelectedDeal(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endHideProfitScaleForSelectedDeal(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHideProfitScaleForSelectedDeal(builder:flatbuffers.Builder):flatbuffers.Offset {
  HideProfitScaleForSelectedDeal.startHideProfitScaleForSelectedDeal(builder);
  return HideProfitScaleForSelectedDeal.endHideProfitScaleForSelectedDeal(builder);
}

unpack(): HideProfitScaleForSelectedDealT {
  return new HideProfitScaleForSelectedDealT();
}


unpackTo(_o: HideProfitScaleForSelectedDealT): void {}
}

export class HideProfitScaleForSelectedDealT {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return HideProfitScaleForSelectedDeal.createHideProfitScaleForSelectedDeal(builder);
}
}
