// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Тип сделки определяем базовую логику отображения и поведения сделки или заявки
 */
export enum DealType {
  CommonRectangle_v2 = 0,
  OpponentBattle = 1,
  Closed = 2,
  Quick = 3,
  CommonRound_v3 = 4,
  OpponentStream = 5,
  OrderByQuote = 6,
  OrderByTime = 7
}
