// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Используется для дополнительной "кастомизации" формы сделки. Поддерживается не всеми типами сделок.
 */
export enum LabelShape {
  Default = 0,
  Rectangle = 1,
  Circle = 2
}
