// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Error, ErrorT } from '../../milky/common/error';
import { VersionInfo, VersionInfoT } from '../../milky/model/version/version-info';
import { ResultsReply, unionToResultsReply, unionListToResultsReply } from '../../milky/version/results-reply';


export class Reply {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Reply {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReply(bb:flatbuffers.ByteBuffer, obj?:Reply):Reply {
  return (obj || new Reply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReply(bb:flatbuffers.ByteBuffer, obj?:Reply):Reply {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Reply()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

resultType():ResultsReply {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ResultsReply.NONE;
}

result<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startReply(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addResultType(builder:flatbuffers.Builder, resultType:ResultsReply) {
  builder.addFieldInt8(0, resultType, ResultsReply.NONE);
}

static addResult(builder:flatbuffers.Builder, resultOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, resultOffset, 0);
}

static endReply(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReply(builder:flatbuffers.Builder, resultType:ResultsReply, resultOffset:flatbuffers.Offset):flatbuffers.Offset {
  Reply.startReply(builder);
  Reply.addResultType(builder, resultType);
  Reply.addResult(builder, resultOffset);
  return Reply.endReply(builder);
}

unpack(): ReplyT {
  return new ReplyT(
    this.resultType(),
    (() => {
      let temp = unionToResultsReply(this.resultType(), this.result.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: ReplyT): void {
  _o.resultType = this.resultType();
  _o.result = (() => {
      let temp = unionToResultsReply(this.resultType(), this.result.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class ReplyT {
constructor(
  public resultType: ResultsReply = ResultsReply.NONE,
  public result: ErrorT|VersionInfoT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const result = builder.createObjectOffset(this.result);

  return Reply.createReply(builder,
    this.resultType,
    result
  );
}
}
