// automatically generated by the FlatBuffers compiler, do not modify

import { AddDealLimits, AddDealLimitsT } from '../../milky/deal-limits/add-deal-limits';
import { RemoveDealLimits, RemoveDealLimitsT } from '../../milky/deal-limits/remove-deal-limits';
import { StopDealLimitsEditing, StopDealLimitsEditingT } from '../../milky/deal-limits/stop-deal-limits-editing';
import { UpdateDealLimits, UpdateDealLimitsT } from '../../milky/deal-limits/update-deal-limits';


export enum Methods {
  NONE = 0,
  AddDealLimits = 1,
  UpdateDealLimits = 2,
  RemoveDealLimits = 3,
  StopDealLimitsEditing = 4
}

export function unionToMethods(
  type: Methods,
  accessor: (obj:AddDealLimits|RemoveDealLimits|StopDealLimitsEditing|UpdateDealLimits) => AddDealLimits|RemoveDealLimits|StopDealLimitsEditing|UpdateDealLimits|null
): AddDealLimits|RemoveDealLimits|StopDealLimitsEditing|UpdateDealLimits|null {
  switch(Methods[type]) {
    case 'NONE': return null; 
    case 'AddDealLimits': return accessor(new AddDealLimits())! as AddDealLimits;
    case 'UpdateDealLimits': return accessor(new UpdateDealLimits())! as UpdateDealLimits;
    case 'RemoveDealLimits': return accessor(new RemoveDealLimits())! as RemoveDealLimits;
    case 'StopDealLimitsEditing': return accessor(new StopDealLimitsEditing())! as StopDealLimitsEditing;
    default: return null;
  }
}

export function unionListToMethods(
  type: Methods, 
  accessor: (index: number, obj:AddDealLimits|RemoveDealLimits|StopDealLimitsEditing|UpdateDealLimits) => AddDealLimits|RemoveDealLimits|StopDealLimitsEditing|UpdateDealLimits|null, 
  index: number
): AddDealLimits|RemoveDealLimits|StopDealLimitsEditing|UpdateDealLimits|null {
  switch(Methods[type]) {
    case 'NONE': return null; 
    case 'AddDealLimits': return accessor(index, new AddDealLimits())! as AddDealLimits;
    case 'UpdateDealLimits': return accessor(index, new UpdateDealLimits())! as UpdateDealLimits;
    case 'RemoveDealLimits': return accessor(index, new RemoveDealLimits())! as RemoveDealLimits;
    case 'StopDealLimitsEditing': return accessor(index, new StopDealLimitsEditing())! as StopDealLimitsEditing;
    default: return null;
  }
}
