// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class StopDealLimitsEditing {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StopDealLimitsEditing {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStopDealLimitsEditing(bb:flatbuffers.ByteBuffer, obj?:StopDealLimitsEditing):StopDealLimitsEditing {
  return (obj || new StopDealLimitsEditing()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStopDealLimitsEditing(bb:flatbuffers.ByteBuffer, obj?:StopDealLimitsEditing):StopDealLimitsEditing {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StopDealLimitsEditing()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startStopDealLimitsEditing(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endStopDealLimitsEditing(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStopDealLimitsEditing(builder:flatbuffers.Builder):flatbuffers.Offset {
  StopDealLimitsEditing.startStopDealLimitsEditing(builder);
  return StopDealLimitsEditing.endStopDealLimitsEditing(builder);
}

unpack(): StopDealLimitsEditingT {
  return new StopDealLimitsEditingT();
}


unpackTo(_o: StopDealLimitsEditingT): void {}
}

export class StopDealLimitsEditingT {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StopDealLimitsEditing.createStopDealLimitsEditing(builder);
}
}
