// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { NotificationLevelId, NotificationLevelIdT } from '../../milky/notification-level/notification-level-id.js';


export class OnRemoved implements flatbuffers.IUnpackableObject<OnRemovedT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OnRemoved {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOnRemoved(bb:flatbuffers.ByteBuffer, obj?:OnRemoved):OnRemoved {
  return (obj || new OnRemoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOnRemoved(bb:flatbuffers.ByteBuffer, obj?:OnRemoved):OnRemoved {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OnRemoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(obj?:NotificationLevelId):NotificationLevelId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NotificationLevelId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startOnRemoved(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static endOnRemoved(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createOnRemoved(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  OnRemoved.startOnRemoved(builder);
  OnRemoved.addId(builder, idOffset);
  return OnRemoved.endOnRemoved(builder);
}

unpack(): OnRemovedT {
  return new OnRemovedT(
    (this.id() !== null ? this.id()!.unpack() : null)
  );
}


unpackTo(_o: OnRemovedT): void {
  _o.id = (this.id() !== null ? this.id()!.unpack() : null);
}
}

export class OnRemovedT implements flatbuffers.IGeneratedObject {
constructor(
  public id: NotificationLevelIdT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? this.id!.pack(builder) : 0);

  return OnRemoved.createOnRemoved(builder,
    id
  );
}
}
