// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class UnselectDeal implements flatbuffers.IUnpackableObject<UnselectDealT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnselectDeal {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnselectDeal(bb:flatbuffers.ByteBuffer, obj?:UnselectDeal):UnselectDeal {
  return (obj || new UnselectDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnselectDeal(bb:flatbuffers.ByteBuffer, obj?:UnselectDeal):UnselectDeal {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnselectDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUnselectDeal(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUnselectDeal(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnselectDeal(builder:flatbuffers.Builder):flatbuffers.Offset {
  UnselectDeal.startUnselectDeal(builder);
  return UnselectDeal.endUnselectDeal(builder);
}

unpack(): UnselectDealT {
  return new UnselectDealT();
}


unpackTo(_o: UnselectDealT): void {}
}

export class UnselectDealT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return UnselectDeal.createUnselectDeal(builder);
}
}
