// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ScrollEnabled implements flatbuffers.IUnpackableObject<ScrollEnabledT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScrollEnabled {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScrollEnabled(bb:flatbuffers.ByteBuffer, obj?:ScrollEnabled):ScrollEnabled {
  return (obj || new ScrollEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScrollEnabled(bb:flatbuffers.ByteBuffer, obj?:ScrollEnabled):ScrollEnabled {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScrollEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

enable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startScrollEnabled(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEnable(builder:flatbuffers.Builder, enable:boolean) {
  builder.addFieldInt8(0, +enable, +false);
}

static endScrollEnabled(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScrollEnabled(builder:flatbuffers.Builder, enable:boolean):flatbuffers.Offset {
  ScrollEnabled.startScrollEnabled(builder);
  ScrollEnabled.addEnable(builder, enable);
  return ScrollEnabled.endScrollEnabled(builder);
}

unpack(): ScrollEnabledT {
  return new ScrollEnabledT(
    this.enable()
  );
}


unpackTo(_o: ScrollEnabledT): void {
  _o.enable = this.enable();
}
}

export class ScrollEnabledT implements flatbuffers.IGeneratedObject {
constructor(
  public enable: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ScrollEnabled.createScrollEnabled(builder,
    this.enable
  );
}
}
