// automatically generated by the FlatBuffers compiler, do not modify

export enum ErrorCode {
  Unknown = 0,
  InvalidStrikeId = 1,
  StrikesEmpty = 2,
  AlreadySelected = 3,
  SelectionStateNotChanged = 4
}
