// automatically generated by the FlatBuffers compiler, do not modify

export { Quote, QuoteT } from './milky/model/quote.js';
export { Time, TimeT } from './milky/model/time.js';
export { Tick, TickT } from './milky/model/quotes/tick.js';
