// automatically generated by the FlatBuffers compiler, do not modify

export { ColorScheme, ColorSchemeT } from './milky/colors/color-scheme.js';
export { ColorTable, ColorTableT } from './milky/colors/color-table.js';
