// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DealId, DealIdT } from '../../milky/model/deal/deal-id';


export class NotifyUnselectDeal {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NotifyUnselectDeal {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNotifyUnselectDeal(bb:flatbuffers.ByteBuffer, obj?:NotifyUnselectDeal):NotifyUnselectDeal {
  return (obj || new NotifyUnselectDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNotifyUnselectDeal(bb:flatbuffers.ByteBuffer, obj?:NotifyUnselectDeal):NotifyUnselectDeal {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NotifyUnselectDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(obj?:DealId):DealId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DealId()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startNotifyUnselectDeal(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, idOffset, 0);
}

static endNotifyUnselectDeal(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createNotifyUnselectDeal(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  NotifyUnselectDeal.startNotifyUnselectDeal(builder);
  NotifyUnselectDeal.addId(builder, idOffset);
  return NotifyUnselectDeal.endNotifyUnselectDeal(builder);
}

unpack(): NotifyUnselectDealT {
  return new NotifyUnselectDealT(
    (this.id() !== null ? this.id()!.unpack() : null)
  );
}


unpackTo(_o: NotifyUnselectDealT): void {
  _o.id = (this.id() !== null ? this.id()!.unpack() : null);
}
}

export class NotifyUnselectDealT {
constructor(
  public id: DealIdT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return NotifyUnselectDeal.createNotifyUnselectDeal(builder,
    (this.id !== null ? this.id!.pack(builder) : 0)
  );
}
}
