// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DealId, DealIdT } from '../../milky/model/deal/deal-id';


export class NotifyUnselectOrder {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NotifyUnselectOrder {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNotifyUnselectOrder(bb:flatbuffers.ByteBuffer, obj?:NotifyUnselectOrder):NotifyUnselectOrder {
  return (obj || new NotifyUnselectOrder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNotifyUnselectOrder(bb:flatbuffers.ByteBuffer, obj?:NotifyUnselectOrder):NotifyUnselectOrder {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NotifyUnselectOrder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(obj?:DealId):DealId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DealId()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startNotifyUnselectOrder(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, idOffset, 0);
}

static endNotifyUnselectOrder(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createNotifyUnselectOrder(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  NotifyUnselectOrder.startNotifyUnselectOrder(builder);
  NotifyUnselectOrder.addId(builder, idOffset);
  return NotifyUnselectOrder.endNotifyUnselectOrder(builder);
}

unpack(): NotifyUnselectOrderT {
  return new NotifyUnselectOrderT(
    (this.id() !== null ? this.id()!.unpack() : null)
  );
}


unpackTo(_o: NotifyUnselectOrderT): void {
  _o.id = (this.id() !== null ? this.id()!.unpack() : null);
}
}

export class NotifyUnselectOrderT {
constructor(
  public id: DealIdT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return NotifyUnselectOrder.createNotifyUnselectOrder(builder,
    (this.id !== null ? this.id!.pack(builder) : 0)
  );
}
}
