// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DealId, DealIdT } from '../../milky/model/deal/deal-id';


export class RemoveDeal {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RemoveDeal {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRemoveDeal(bb:flatbuffers.ByteBuffer, obj?:RemoveDeal):RemoveDeal {
  return (obj || new RemoveDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRemoveDeal(bb:flatbuffers.ByteBuffer, obj?:RemoveDeal):RemoveDeal {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RemoveDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(obj?:DealId):DealId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DealId()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startRemoveDeal(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, idOffset, 0);
}

static endRemoveDeal(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createRemoveDeal(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  RemoveDeal.startRemoveDeal(builder);
  RemoveDeal.addId(builder, idOffset);
  return RemoveDeal.endRemoveDeal(builder);
}

unpack(): RemoveDealT {
  return new RemoveDealT(
    (this.id() !== null ? this.id()!.unpack() : null)
  );
}


unpackTo(_o: RemoveDealT): void {
  _o.id = (this.id() !== null ? this.id()!.unpack() : null);
}
}

export class RemoveDealT {
constructor(
  public id: DealIdT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RemoveDeal.createRemoveDeal(builder,
    (this.id !== null ? this.id!.pack(builder) : 0)
  );
}
}
