// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Используется для дополнительной "кастомизации" сделки. Поддерживается не всеми типами сделок.
 */
export enum LabelLayout {
  Default = 0,
  LeftView = 1,
  BottomView = 2,
  GridView = 3,
  LeftOpenPoint = 4,
}
