// automatically generated by the FlatBuffers compiler, do not modify

import { ListAreas, ListAreasT } from '../../milky/model/layout/list-areas';


export enum Notifies {
  NONE = 0,
  model_layout_ListAreas = 1
}

export function unionToNotifies(
  type: Notifies,
  accessor: (obj:ListAreas) => ListAreas|null
): ListAreas|null {
  switch(Notifies[type]) {
    case 'NONE': return null; 
    case 'model_layout_ListAreas': return accessor(new ListAreas())! as ListAreas;
    default: return null;
  }
}

export function unionListToNotifies(
  type: Notifies, 
  accessor: (index: number, obj:ListAreas) => ListAreas|null, 
  index: number
): ListAreas|null {
  switch(Notifies[type]) {
    case 'NONE': return null; 
    case 'model_layout_ListAreas': return accessor(index, new ListAreas())! as ListAreas;
    default: return null;
  }
}
