// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Выглядит лишним: пока не ясно на что это может влиять.
 */
export enum TradingMechanics {
  Forex = 0,
  DigitalOptions = 1,
  Stock = 2
}
