// automatically generated by the FlatBuffers compiler, do not modify

export enum StaticResourceType {
  Undefined = 0,
  FontDefault = 1,
  FontBold = 2,
  AtlasSDpng = 3,
  AtlasSDjson = 4,
  AtlasHDpng = 5,
  AtlasHDjson = 6,
  AtlasXHDpng = 7,
  AtlasXHDjson = 8
}
