// automatically generated by the FlatBuffers compiler, do not modify

export { Amount, AmountT } from './milky/model/amount';
export { IconType, IconTypeT } from './milky/model/icon-type';
export { Quote, QuoteT } from './milky/model/quote';
export { Rect, RectT } from './milky/model/rect';
export { Time, TimeT } from './milky/model/time';
