// automatically generated by the FlatBuffers compiler, do not modify

export { FinishOnboarding, FinishOnboardingT } from './milky/onboarding/finish-onboarding';
export { FinishOnboardingDeal, FinishOnboardingDealT } from './milky/onboarding/finish-onboarding-deal';
export { HideDirectionsAreas, HideDirectionsAreasT } from './milky/onboarding/hide-directions-areas';
export { HidePossibleCharts, HidePossibleChartsT } from './milky/onboarding/hide-possible-charts';
export { Methods, unionToMethods, unionListToMethods } from './milky/onboarding/methods';
export { Request, RequestT } from './milky/onboarding/request';
export { ShowDirectionsAreas, ShowDirectionsAreasT } from './milky/onboarding/show-directions-areas';
export { ShowPossibleCharts, ShowPossibleChartsT } from './milky/onboarding/show-possible-charts';
export { StartLastCandleAnimation, StartLastCandleAnimationT } from './milky/onboarding/start-last-candle-animation';
export { StartOnboarding, StartOnboardingT } from './milky/onboarding/start-onboarding';
export { StopLastCandleAnimation, StopLastCandleAnimationT } from './milky/onboarding/stop-last-candle-animation';
