// automatically generated by the FlatBuffers compiler, do not modify

export { Quote, QuoteT } from './milky/model/quote';
export { Strike, StrikeT } from './milky/model/strike/strike';
export { StrikeId, StrikeIdT } from './milky/model/strike/strike-id';
