// automatically generated by the FlatBuffers compiler, do not modify

export { ApiVersion, ApiVersionT } from './milky/model/version/api-version';
export { VersionInfo, VersionInfoT } from './milky/model/version/version-info';
