// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class DealTopUpEnabled {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DealTopUpEnabled {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDealTopUpEnabled(bb:flatbuffers.ByteBuffer, obj?:DealTopUpEnabled):DealTopUpEnabled {
  return (obj || new DealTopUpEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDealTopUpEnabled(bb:flatbuffers.ByteBuffer, obj?:DealTopUpEnabled):DealTopUpEnabled {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DealTopUpEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

enable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startDealTopUpEnabled(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEnable(builder:flatbuffers.Builder, enable:boolean) {
  builder.addFieldInt8(0, +enable, +false);
}

static endDealTopUpEnabled(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDealTopUpEnabled(builder:flatbuffers.Builder, enable:boolean):flatbuffers.Offset {
  DealTopUpEnabled.startDealTopUpEnabled(builder);
  DealTopUpEnabled.addEnable(builder, enable);
  return DealTopUpEnabled.endDealTopUpEnabled(builder);
}

unpack(): DealTopUpEnabledT {
  return new DealTopUpEnabledT(
    this.enable()
  );
}


unpackTo(_o: DealTopUpEnabledT): void {
  _o.enable = this.enable();
}
}

export class DealTopUpEnabledT {
constructor(
  public enable: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return DealTopUpEnabled.createDealTopUpEnabled(builder,
    this.enable
  );
}
}
