// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class OptionProfitDownValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OptionProfitDownValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOptionProfitDownValue(bb:flatbuffers.ByteBuffer, obj?:OptionProfitDownValue):OptionProfitDownValue {
  return (obj || new OptionProfitDownValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOptionProfitDownValue(bb:flatbuffers.ByteBuffer, obj?:OptionProfitDownValue):OptionProfitDownValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OptionProfitDownValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startOptionProfitDownValue(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldInt32(0, value, 0);
}

static endOptionProfitDownValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOptionProfitDownValue(builder:flatbuffers.Builder, value:number):flatbuffers.Offset {
  OptionProfitDownValue.startOptionProfitDownValue(builder);
  OptionProfitDownValue.addValue(builder, value);
  return OptionProfitDownValue.endOptionProfitDownValue(builder);
}

unpack(): OptionProfitDownValueT {
  return new OptionProfitDownValueT(
    this.value()
  );
}


unpackTo(_o: OptionProfitDownValueT): void {
  _o.value = this.value();
}
}

export class OptionProfitDownValueT {
constructor(
  public value: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return OptionProfitDownValue.createOptionProfitDownValue(builder,
    this.value
  );
}
}
