// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ProfitScaleEnabled {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProfitScaleEnabled {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProfitScaleEnabled(bb:flatbuffers.ByteBuffer, obj?:ProfitScaleEnabled):ProfitScaleEnabled {
  return (obj || new ProfitScaleEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProfitScaleEnabled(bb:flatbuffers.ByteBuffer, obj?:ProfitScaleEnabled):ProfitScaleEnabled {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProfitScaleEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

enable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startProfitScaleEnabled(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEnable(builder:flatbuffers.Builder, enable:boolean) {
  builder.addFieldInt8(0, +enable, +false);
}

static endProfitScaleEnabled(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProfitScaleEnabled(builder:flatbuffers.Builder, enable:boolean):flatbuffers.Offset {
  ProfitScaleEnabled.startProfitScaleEnabled(builder);
  ProfitScaleEnabled.addEnable(builder, enable);
  return ProfitScaleEnabled.endProfitScaleEnabled(builder);
}

unpack(): ProfitScaleEnabledT {
  return new ProfitScaleEnabledT(
    this.enable()
  );
}


unpackTo(_o: ProfitScaleEnabledT): void {
  _o.enable = this.enable();
}
}

export class ProfitScaleEnabledT {
constructor(
  public enable: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ProfitScaleEnabled.createProfitScaleEnabled(builder,
    this.enable
  );
}
}
