// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class SentimentEnable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SentimentEnable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSentimentEnable(bb:flatbuffers.ByteBuffer, obj?:SentimentEnable):SentimentEnable {
  return (obj || new SentimentEnable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSentimentEnable(bb:flatbuffers.ByteBuffer, obj?:SentimentEnable):SentimentEnable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SentimentEnable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

enable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startSentimentEnable(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEnable(builder:flatbuffers.Builder, enable:boolean) {
  builder.addFieldInt8(0, +enable, +false);
}

static endSentimentEnable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSentimentEnable(builder:flatbuffers.Builder, enable:boolean):flatbuffers.Offset {
  SentimentEnable.startSentimentEnable(builder);
  SentimentEnable.addEnable(builder, enable);
  return SentimentEnable.endSentimentEnable(builder);
}

unpack(): SentimentEnableT {
  return new SentimentEnableT(
    this.enable()
  );
}


unpackTo(_o: SentimentEnableT): void {
  _o.enable = this.enable();
}
}

export class SentimentEnableT {
constructor(
  public enable: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return SentimentEnable.createSentimentEnable(builder,
    this.enable
  );
}
}
