// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class StopOrderEditModeEnabled {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StopOrderEditModeEnabled {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStopOrderEditModeEnabled(bb:flatbuffers.ByteBuffer, obj?:StopOrderEditModeEnabled):StopOrderEditModeEnabled {
  return (obj || new StopOrderEditModeEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStopOrderEditModeEnabled(bb:flatbuffers.ByteBuffer, obj?:StopOrderEditModeEnabled):StopOrderEditModeEnabled {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StopOrderEditModeEnabled()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

enable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startStopOrderEditModeEnabled(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEnable(builder:flatbuffers.Builder, enable:boolean) {
  builder.addFieldInt8(0, +enable, +false);
}

static endStopOrderEditModeEnabled(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStopOrderEditModeEnabled(builder:flatbuffers.Builder, enable:boolean):flatbuffers.Offset {
  StopOrderEditModeEnabled.startStopOrderEditModeEnabled(builder);
  StopOrderEditModeEnabled.addEnable(builder, enable);
  return StopOrderEditModeEnabled.endStopOrderEditModeEnabled(builder);
}

unpack(): StopOrderEditModeEnabledT {
  return new StopOrderEditModeEnabledT(
    this.enable()
  );
}


unpackTo(_o: StopOrderEditModeEnabledT): void {
  _o.enable = this.enable();
}
}

export class StopOrderEditModeEnabledT {
constructor(
  public enable: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StopOrderEditModeEnabled.createStopOrderEditModeEnabled(builder,
    this.enable
  );
}
}
