// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import type { DealIdT } from '../../milky/model/deal/deal-id.js';
import { DealId } from '../../milky/model/deal/deal-id.js';

export class NotifySelectOrder implements flatbuffers.IUnpackableObject<NotifySelectOrderT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): NotifySelectOrder {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsNotifySelectOrder(bb: flatbuffers.ByteBuffer, obj?: NotifySelectOrder): NotifySelectOrder {
    return (obj || new NotifySelectOrder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsNotifySelectOrder(
    bb: flatbuffers.ByteBuffer,
    obj?: NotifySelectOrder,
  ): NotifySelectOrder {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new NotifySelectOrder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  id(obj?: DealId): DealId | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? (obj || new DealId()).__init(this.bb_pos + offset, this.bb!) : null;
  }

  static startNotifySelectOrder(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addId(builder: flatbuffers.Builder, idOffset: flatbuffers.Offset) {
    builder.addFieldStruct(0, idOffset, 0);
  }

  static endNotifySelectOrder(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    builder.requiredField(offset, 4); // id
    return offset;
  }

  static createNotifySelectOrder(builder: flatbuffers.Builder, idOffset: flatbuffers.Offset): flatbuffers.Offset {
    NotifySelectOrder.startNotifySelectOrder(builder);
    NotifySelectOrder.addId(builder, idOffset);
    return NotifySelectOrder.endNotifySelectOrder(builder);
  }

  unpack(): NotifySelectOrderT {
    return new NotifySelectOrderT(this.id() !== null ? this.id()!.unpack() : null);
  }

  unpackTo(_o: NotifySelectOrderT): void {
    _o.id = this.id() !== null ? this.id()!.unpack() : null;
  }
}

export class NotifySelectOrderT implements flatbuffers.IGeneratedObject {
  constructor(public id: DealIdT | null = null) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    return NotifySelectOrder.createNotifySelectOrder(builder, this.id !== null ? this.id.pack(builder) : 0);
  }
}
