// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import type { DealIdT } from '../../milky/model/deal/deal-id.js';
import { DealId } from '../../milky/model/deal/deal-id.js';

export class SelectDeal implements flatbuffers.IUnpackableObject<SelectDealT> {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SelectDeal {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSelectDeal(bb: flatbuffers.ByteBuffer, obj?: SelectDeal): SelectDeal {
    return (obj || new SelectDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsSelectDeal(bb: flatbuffers.ByteBuffer, obj?: SelectDeal): SelectDeal {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SelectDeal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  id(obj?: DealId): DealId | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? (obj || new DealId()).__init(this.bb_pos + offset, this.bb!) : null;
  }

  static startSelectDeal(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addId(builder: flatbuffers.Builder, idOffset: flatbuffers.Offset) {
    builder.addFieldStruct(0, idOffset, 0);
  }

  static endSelectDeal(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    builder.requiredField(offset, 4); // id
    return offset;
  }

  static createSelectDeal(builder: flatbuffers.Builder, idOffset: flatbuffers.Offset): flatbuffers.Offset {
    SelectDeal.startSelectDeal(builder);
    SelectDeal.addId(builder, idOffset);
    return SelectDeal.endSelectDeal(builder);
  }

  unpack(): SelectDealT {
    return new SelectDealT(this.id() !== null ? this.id()!.unpack() : null);
  }

  unpackTo(_o: SelectDealT): void {
    _o.id = this.id() !== null ? this.id()!.unpack() : null;
  }
}

export class SelectDealT implements flatbuffers.IGeneratedObject {
  constructor(public id: DealIdT | null = null) {}

  pack(builder: flatbuffers.Builder): flatbuffers.Offset {
    return SelectDeal.createSelectDeal(builder, this.id !== null ? this.id.pack(builder) : 0);
  }
}
