// automatically generated by the FlatBuffers compiler, do not modify

import { Notify as milky_adviser_Notify, NotifyT as milky_adviser_NotifyT } from '../milky/adviser/notify';
import { Notify as milky_deal_limits_Notify, NotifyT as milky_deal_limits_NotifyT } from '../milky/deal-limits/notify';
import { Notify, NotifyT } from '../milky/deals/notify';
import { Notify as milky_drawing_Notify, NotifyT as milky_drawing_NotifyT } from '../milky/drawing/notify';
import { Notify as milky_layout_Notify, NotifyT as milky_layout_NotifyT } from '../milky/layout/notify';
import { Notify as milky_notification_level_Notify, NotifyT as milky_notification_level_NotifyT } from '../milky/notification-level/notify';
import { Notify as milky_quotes_Notify, NotifyT as milky_quotes_NotifyT } from '../milky/quotes/notify';
import { Notify as milky_resources_Notify, NotifyT as milky_resources_NotifyT } from '../milky/resources/notify';
import { Notify as milky_strikes_Notify, NotifyT as milky_strikes_NotifyT } from '../milky/strikes/notify';
import { Notify as milky_time_intervals_Notify, NotifyT as milky_time_intervals_NotifyT } from '../milky/time-intervals/notify';


export enum RequestFromChart {
  NONE = 0,
  deals_Notify = 1,
  resources_Notify = 2,
  drawing_Notify = 3,
  quotes_Notify = 4,
  adviser_Notify = 5,
  notification_level_Notify = 6,
  strikes_Notify = 7,
  time_intervals_Notify = 8,
  deal_limits_Notify = 9,
  layout_Notify = 10
}

export function unionToRequestFromChart(
  type: RequestFromChart,
  accessor: (obj:Notify|milky_adviser_Notify|milky_deal_limits_Notify|milky_drawing_Notify|milky_layout_Notify|milky_notification_level_Notify|milky_quotes_Notify|milky_resources_Notify|milky_strikes_Notify|milky_time_intervals_Notify) => Notify|milky_adviser_Notify|milky_deal_limits_Notify|milky_drawing_Notify|milky_layout_Notify|milky_notification_level_Notify|milky_quotes_Notify|milky_resources_Notify|milky_strikes_Notify|milky_time_intervals_Notify|null
): Notify|milky_adviser_Notify|milky_deal_limits_Notify|milky_drawing_Notify|milky_layout_Notify|milky_notification_level_Notify|milky_quotes_Notify|milky_resources_Notify|milky_strikes_Notify|milky_time_intervals_Notify|null {
  switch(RequestFromChart[type]) {
    case 'NONE': return null; 
    case 'deals_Notify': return accessor(new Notify())! as Notify;
    case 'resources_Notify': return accessor(new milky_resources_Notify())! as milky_resources_Notify;
    case 'drawing_Notify': return accessor(new milky_drawing_Notify())! as milky_drawing_Notify;
    case 'quotes_Notify': return accessor(new milky_quotes_Notify())! as milky_quotes_Notify;
    case 'adviser_Notify': return accessor(new milky_adviser_Notify())! as milky_adviser_Notify;
    case 'notification_level_Notify': return accessor(new milky_notification_level_Notify())! as milky_notification_level_Notify;
    case 'strikes_Notify': return accessor(new milky_strikes_Notify())! as milky_strikes_Notify;
    case 'time_intervals_Notify': return accessor(new milky_time_intervals_Notify())! as milky_time_intervals_Notify;
    case 'deal_limits_Notify': return accessor(new milky_deal_limits_Notify())! as milky_deal_limits_Notify;
    case 'layout_Notify': return accessor(new milky_layout_Notify())! as milky_layout_Notify;
    default: return null;
  }
}

export function unionListToRequestFromChart(
  type: RequestFromChart, 
  accessor: (index: number, obj:Notify|milky_adviser_Notify|milky_deal_limits_Notify|milky_drawing_Notify|milky_layout_Notify|milky_notification_level_Notify|milky_quotes_Notify|milky_resources_Notify|milky_strikes_Notify|milky_time_intervals_Notify) => Notify|milky_adviser_Notify|milky_deal_limits_Notify|milky_drawing_Notify|milky_layout_Notify|milky_notification_level_Notify|milky_quotes_Notify|milky_resources_Notify|milky_strikes_Notify|milky_time_intervals_Notify|null, 
  index: number
): Notify|milky_adviser_Notify|milky_deal_limits_Notify|milky_drawing_Notify|milky_layout_Notify|milky_notification_level_Notify|milky_quotes_Notify|milky_resources_Notify|milky_strikes_Notify|milky_time_intervals_Notify|null {
  switch(RequestFromChart[type]) {
    case 'NONE': return null; 
    case 'deals_Notify': return accessor(index, new Notify())! as Notify;
    case 'resources_Notify': return accessor(index, new milky_resources_Notify())! as milky_resources_Notify;
    case 'drawing_Notify': return accessor(index, new milky_drawing_Notify())! as milky_drawing_Notify;
    case 'quotes_Notify': return accessor(index, new milky_quotes_Notify())! as milky_quotes_Notify;
    case 'adviser_Notify': return accessor(index, new milky_adviser_Notify())! as milky_adviser_Notify;
    case 'notification_level_Notify': return accessor(index, new milky_notification_level_Notify())! as milky_notification_level_Notify;
    case 'strikes_Notify': return accessor(index, new milky_strikes_Notify())! as milky_strikes_Notify;
    case 'time_intervals_Notify': return accessor(index, new milky_time_intervals_Notify())! as milky_time_intervals_Notify;
    case 'deal_limits_Notify': return accessor(index, new milky_deal_limits_Notify())! as milky_deal_limits_Notify;
    case 'layout_Notify': return accessor(index, new milky_layout_Notify())! as milky_layout_Notify;
    default: return null;
  }
}
